version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: papergraph
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
volumes:
  db_data: 